// export { sum, multiplication, countStringSymbols } from "./Homework1/task1";
// export { sumUserNumber } from "./Homework1/task1_3";
// export { monthsPresented } from "./Homework2/task2_3";
// export { isCircleFitToSquare, maxNumber } from "./Homework2/task2";
// export { sumNaturalNumbers, multiplacationTable } from "./Homework3/task3";
// export { arithmeticMean } from "./Homework3/task3_3";
export * from "./Homework1/task1";
export * from "./Homework1/task1_3";
export * from "./Homework2/task2";
export * from "./Homework2/task2_3";
export * from "./Homework3/task3";
export * from "./Homework3/task3_3";
